export const ACTION_TYPES = {
  LOG_IN : "LOG_IN",
  LOG_OUT : "LOG_OUT",

  SET_INPUT_VALUE: "SET_INPUT_VALUE",
  RESET_INPUT: "RESET_INPUT",
  SET_INPUT_ERROR_MESSAGE: "SET_INPUT_ERROR_MESSAGE",
  
  SET_FETCHED_LIST_VALUES : "SET_FETCHED_LIST_VALUES",
  START_FETCHING: "START_FETCHING",
  FETCHING_SUCCESS: "FETCHING_SUCCESS",
  FETCHING_ERROR: "FETCHING_ERROR",
}